redis:
    container_name: redis
    image: demoregistry.dataman-inc.com/srypoc/redis:3.0.5
    command: redis-server --appendonly yes
    expose:
      - "6379" 
    restart: always

rmq:
    container_name: rmq
    image: demoregistry.dataman-inc.com/srypoc/rabbitmq:3.6.0-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
      - "15671"
      - "15672"
    restart: always

mysql:
    container_name: mysql
    image: demoregistry.dataman-inc.com/srypoc/mysql:5.6
    volumes:
      - ./src/omega-cluster/omega/omega/mysql_settings/my.cnf:/etc/my.cnf:ro
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=bignibou
    expose:
      - "3306"
    restart: always

influxdb:
  image: demoregistry.dataman-inc.com/srypoc/influxdb:0.10
  environment:
    - PRE_CREATE_DB=shurenyun
  container_name: influxdb
  restart: always

elasticsearch:
  image: demoregistry.dataman-inc.com/srypoc/centos7-jdk7-elasticsearch-1.4.5-alone:20160522230210
  environment:
    - ES_MIN_MEM=1024M
    - ES_MAX_MEM=1024M
  container_name: elasticsearch
  restart: always

logstash:
  container_name: logstash
  image: demoregistry.dataman-inc.com/srypoc/logstash:1.5.6
  volumes:
    - ./src/omega-es/third_party/logstash/dataman.conf:/etc/logstash/conf.d/dataman.conf
    - ./src/omega-es/third_party/logstash/logstash.json:/usr/local/logstash/conf/logstash.json
  command: logstash -f /etc/logstash/conf.d/dataman.conf
  links:
    - elasticsearch
  restart: always

####################################################################################################################
harbor:
  container_name: harbor
  build: ./src/harbor/
  volumes:
    - ./src/harbor/Deploy/Omega/ui/:/etc/ui
    - ./src/harbor/sql/:/sql
  environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_USR=root
    - MYSQL_PWD=111111
    - REGISTRY_URL=http://registry:5000
    - CONFIG_PATH=/etc/ui/app.conf
    - HARBOR_REG_URL=http://registry:5000
    - HARBOR_ADMIN_PASSWORD=Harbor12345
    - HARBOR_URL=http://harbor:5005
    - AUTH_MODE=db_auth
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - SQL_PATH=/sql
  links:
    - redis
    - mysql
  extra_hosts:
    - "registry:192.168.1.159"
  restart: always

registry:
  container_name: registry
  image: demoregistry.dataman-inc.com/srypoc/registry:2.3.0
  volumes:
    - ./src/harbor/Deploy/Omega/registry/:/etc/registry/
  command:
    - /etc/registry/config.yml
  links:
    - harbor
  restart: always
drone:
  container_name: drone
  build: src/drone
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/drone/drone.sqlite:/var/lib/drone/drone.sqlite
    - ./src/drone/.env.sample:/go/src/github.com/drone/drone/.env
  links:
    - harbor
    - registry
    - mysql
  restart: always

####################################################################################################################

cluster:
  container_name: cluster
  build: ./src/omega-cluster/omega/
  volumes:
    - ./src/omega-cluster/omega/:/code
  links:
    - mysql
    - redis
    - rmq
  expose:
    - 8888
    - 8000
  restart: always

app:
  container_name: app
  build: ./src/omega-app/
  volumes:
    - ./src/omega-app/omega-app.yaml.sample:/etc/omega/omega-app.yaml:ro
  links:
    - mysql
    - redis
    - rmq
    - drone
    - harbor
    - registry
  restart: always

metrics:
  container_name: metrics
  build: ./src/omega-metrics
  volumes:
    - ./src/omega-metrics/omega-metrics.yaml.sample:/etc/omega/omega-metrics.yaml:ro
  links:
    - app
    - redis
    - rmq
    - influxdb
  restart: always
logging:
  container_name: logging 
  build: ./src/omega-es
  volumes:
    - ./src/omega-es/omega-es.yaml.sample:/etc/omega/omega-es.yaml:ro
  links:
    - redis
    - mysql
    - elasticsearch
  restart: always

billing:
  container_name: billing
  build: ./src/omega-billing
  volumes:
    - ./src/omega-billing/omega-billing.yaml.sample:/etc/omega/omega-billing.yaml:ro
  links:
    - mysql
    - redis
    - rmq
  restart: always

alert:
  container_name: alert
  build: ./src/sryun-alert
  environment:
    DB_ADDR: "mysql:3306"
    DB_USER: "root"
    DB_PASSWORD: "111111"
    INFLUX_ADDR: "http://influxdb:5008"
    AUTH_ADDR: "http://cluster:8888/api/v3/user"
    SMTP_ADDR: "http://cluster:8888/api/v3/email"
    CACHE_ADDR: "redis:6379"
    APP_ADDR: "http://app:6080"
    KAPACITOR_HOSTNAME: "influxdb"
    KAPACITOR_INFLUXDB: "http://influxdb:5008"
  links:
    - mysql
    - influxdb
    - cluster
    - redis
    - app

  restart: always

#####################################################################################################

frontend:
  image: index.shurenyun.com/zqdou/nginx:1.9.6
  container_name: frontend 
  volumes:
    - ./src/frontend/glance:/usr/share/nginx/html:ro
    - ./src/frontend/conf/dataman/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./src/frontend/conf/dataman/ssl/ssl_certificate.crt:/etc/nginx/ssl_certificate.crt:ro
    - ./src/frontend/conf/dataman/ssl/www.dataman.io-no-passphrase.key:/etc/nginx/www.dataman.io-no-passphrase.key:ro
  links:
    - cluster
    - harbor
    - app
    - logging 
    - billing
    - metrics
    - elasticsearch
    - alert
  ports:
    - "8000:80"
  restart: always
