CREATE DATABASE IF NOT EXISTS omega;
CREATE DATABASE IF NOT EXISTS alarm;
CREATE DATABASE IF NOT EXISTS oapp;
CREATE DATABASE IF NOT EXISTS alert;
CREATE DATABASE IF NOT EXISTS drone;
CREATE DATABASE IF NOT EXISTS billing;
CREATE DATABASE IF NOT EXISTS registry;

